// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvzfgweidgujlcpxzrdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2emZnd2VpZGd1amxjcHh6cmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Njc1NDYsImV4cCI6MjA1OTQ0MzU0Nn0.L0xgBXsyDfUbci10f6Wm4vD_DXOM1uk_0XQpZizutFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);